### ISSUE TITLE
PHPStan 2.0 support

### ISSUE THREAD

**Issue by wietsewarendorff** [bladestan/bladestan#118]
Hi there, any plans to support phpstan 2?

**Comment by wietsewarendorff** [comment]
sure, would love to help, is there an overview of things to be done (or is that the first item on the list :) )?

**Comment by AJenbo** [comment]
If you go over the open Pull request you will see that they are mostly failing test cases for features that we haven't yet implemented.

It would be really nice if we could do so before moving to a new version of phpstan.

I plan to do another release for phpstan 1.x right before applying anything breaking, and I will probably start the migration in a month when I'm done adjusting the systems I work on to the phpstan 2 changes (I have already moved 1/3 to bleeding edge in 1.x)

**Comment by AJenbo** [comment]
0.6.0 is out now with all the latest improvements for PHPStan 1.x, I have started development on supporting PHPStan 2.x in https://github.com/TomasVotruba/bladestan/tree/phpstan2 so fare it's installable but does not work, more to come :)

**Comment by AJenbo** [comment]
@TomasVotruba will you announce to the world that there is a new release on your SOME channels :)

**Comment by TomasVotruba** [comment]
Sure 😊, make a tweet and ping me, I'll share it further 🏎️

**Comment by AJenbo** [comment]
@wietsewarendorff the phpstan2 branch now works with PHPStan 2, there is still a bit of clean up to do, but if you can test things out that would be helpful.

**Comment by TomasVotruba** [comment]
@AJenbo Thanks!
Feels wrong to see my face there, since you're doing all the work :)

I'm trying to move repository to your name, but same-named repository already forked. Could you remove it? 

I've also added you as a maintainer on packagist 👍

**Comment by AJenbo** [comment]
> Could you remove it?

@TomasVotruba done

**Comment by AJenbo** [comment]
Done: https://github.com/bladestan
![image](https://github.com/user-attachments/assets/7f3e30e5-b630-4c80-b38f-362baf500cb6)

**Comment by TomasVotruba** [comment]
Awesome :clap:  Just moved it there: https://github.com/bladestan/bladestan

I'll leave the org, as I have to focus on Rector ecosystem now and I'm removing any distractions now. 
Thanks for creating it :+1:

**Comment by TomasVotruba** [comment]
Here is a "retweet" to spread the news :)  

https://x.com/VotrubaT/status/1868337395340607959

**Comment by AJenbo** [comment]
Thanks, and changes for getting this project up and running :)
